version: '3'

services:

  app:
    build: .
    volumes:
      - .:/code

    working_dir: /code

    ports:
      - 8000:8000
      - 7000:7000

    command: make

    depends_on:
      - database

    command: make

    environment:

      - DATABASE_URL=postgres://user:secret@database:5432/db

  database:
    image: postgres:10-alpine

    ports:
      - 8001:5432

    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=secret

